-- MySQL Script generated by MySQL Workbench
-- Tue Jun 17 09:35:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema waifudb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema waifudb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `waifudb` DEFAULT CHARACTER SET utf8mb3 ;
USE `waifudb` ;

-- -----------------------------------------------------
-- Table `waifudb`.`waifu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waifudb`.`waifu` (
  `WaifuID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Origin` VARCHAR(100) NULL DEFAULT NULL,
  `Personality` VARCHAR(100) NULL DEFAULT NULL,
  `Appearance` TEXT NULL DEFAULT NULL,
  `Popularity` DECIMAL(3,1) NULL DEFAULT NULL,
  `ImagePath` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Relative path to the waifu card image, e.g., /cards/waifu1.png',
  PRIMARY KEY (`WaifuID`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `waifudb`.`abilities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waifudb`.`abilities` (
  `AbilityID` INT NOT NULL AUTO_INCREMENT,
  `WaifuID` INT NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Type` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`AbilityID`),
  INDEX `fk_abilities_waifu_idx` (`WaifuID` ASC) VISIBLE,
  CONSTRAINT `fk_abilities_waifu`
    FOREIGN KEY (`WaifuID`)
    REFERENCES `waifudb`.`waifu` (`WaifuID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `waifudb`.`fandom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waifudb`.`fandom` (
  `FandomID` INT NOT NULL AUTO_INCREMENT,
  `WaifuID` INT NOT NULL,
  `FanClubName` VARCHAR(100) NOT NULL,
  `MemberCount` INT NULL DEFAULT NULL,
  `Platform` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`FandomID`),
  INDEX `fk_fandom_waifu_idx` (`WaifuID` ASC) VISIBLE,
  CONSTRAINT `fk_fandom_waifu`
    FOREIGN KEY (`WaifuID`)
    REFERENCES `waifudb`.`waifu` (`WaifuID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `waifudb`.`studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waifudb`.`studio` (
  `StudioID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Location` VARCHAR(100) NULL DEFAULT NULL,
  `FoundedYear` INT NULL DEFAULT NULL,
  PRIMARY KEY (`StudioID`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `waifudb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waifudb`.`media` (
  `MediaID` INT NOT NULL AUTO_INCREMENT,
  `WaifuID` INT NOT NULL,
  `StudioID` INT NOT NULL,
  `Title` VARCHAR(100) NOT NULL,
  `Type` VARCHAR(50) NULL DEFAULT NULL,
  `ReleaseYear` INT NULL DEFAULT NULL,
  PRIMARY KEY (`MediaID`),
  INDEX `fk_media_waifu_idx` (`WaifuID` ASC) VISIBLE,
  INDEX `fk_media_studio_idx` (`StudioID` ASC) VISIBLE,
  CONSTRAINT `fk_media_studio`
    FOREIGN KEY (`StudioID`)
    REFERENCES `waifudb`.`studio` (`StudioID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_media_waifu`
    FOREIGN KEY (`WaifuID`)
    REFERENCES `waifudb`.`waifu` (`WaifuID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `waifudb`.`merchandise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waifudb`.`merchandise` (
  `MerchID` INT NOT NULL AUTO_INCREMENT,
  `WaifuID` INT NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Type` VARCHAR(50) NULL DEFAULT NULL,
  `Price` DECIMAL(10,2) NULL DEFAULT NULL,
  `ReleaseDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`MerchID`),
  INDEX `fk_merchandise_waifu_idx` (`WaifuID` ASC) VISIBLE,
  CONSTRAINT `fk_merchandise_waifu`
    FOREIGN KEY (`WaifuID`)
    REFERENCES `waifudb`.`waifu` (`WaifuID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `waifudb`.`voiceactor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waifudb`.`voiceactor` (
  `VoiceActorID` INT NOT NULL AUTO_INCREMENT,
  `WaifuID` INT NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Nationality` VARCHAR(50) NULL DEFAULT NULL,
  `Agency` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`VoiceActorID`),
  INDEX `fk_voiceactor_waifu_idx` (`WaifuID` ASC) VISIBLE,
  CONSTRAINT `fk_voiceactor_waifu`
    FOREIGN KEY (`WaifuID`)
    REFERENCES `waifudb`.`waifu` (`WaifuID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
